"""
Test 9: Comparison of the two hairpin lists used in test3_newdataset_withEmboss
and test3_newdataset_withPA.

  - EMBOSS list : generated by EMBOSS palindrome via config.yaml stem/loop params
  - PA list     : fixed file input/palindrom_analyzer_output.txt

Hairpin identity is defined by (start, stem_length, spacer_length, mismatches).
The script reports:
  1. Counts and parameter distributions for each list
  2. Set overlap: shared / EMBOSS-only / PA-only
  3. Distribution of differences by stem length, loop length, mismatch count
  4. Plots saved to test9/
"""

import sys
import os
from pathlib import Path
from collections import Counter, defaultdict

BINOMIAL_DIR = Path(__file__).parent.parent.parent / "binomial"
PA_FILE      = "/Users/mar/BIO/PROJECTS/MPOX/COMMENT/APOBEC3-Mpox-IRs/input/palindrom_analyzer_output.txt"

sys.path.insert(0, str(BINOMIAL_DIR))
os.chdir(BINOMIAL_DIR)

# ── load EMBOSS hairpin list (no hairpins_path → runs EMBOSS) ─────────────────
import yaml as _yaml
_orig = _yaml.safe_load
def _no_pa(s):
    r = _orig(s); r.pop("hairpins_path", None) if isinstance(r, dict) else None; return r
_yaml.safe_load = _no_pa
import load
_yaml.safe_load = _orig

emboss_list = load.all_hairpins_list
print(f"EMBOSS list : {len(emboss_list):,} hairpins")

# ── load PA hairpin list directly ─────────────────────────────────────────────
pa_list = load.load_hairpins(PA_FILE)
print(f"PA list     : {len(pa_list):,} hairpins")

# ── identity key: (start, stem_length, spacer_length, mismatches) ─────────────
def key(h):
    return (h.start, h.stem_length, h.spacer_length, h.miss)

emboss_keys = {key(h) for h in emboss_list}
pa_keys     = {key(h) for h in pa_list}

shared       = emboss_keys & pa_keys
emboss_only  = emboss_keys - pa_keys
pa_only      = pa_keys     - emboss_keys

print(f"\nShared      : {len(shared):,}")
print(f"EMBOSS only : {len(emboss_only):,}")
print(f"PA only     : {len(pa_only):,}")

# ── distribution analysis ─────────────────────────────────────────────────────
def dist(keys, idx):
    return Counter(k[idx] for k in keys)

# idx: 1=stem, 2=loop, 3=miss
for label, keys in [("EMBOSS-only", emboss_only), ("PA-only", pa_only)]:
    print(f"\n── {label} ──")
    print(f"  by stem  : {dict(sorted(dist(keys,1).items()))}")
    print(f"  by loop  : {dict(sorted(dist(keys,2).items()))}")
    print(f"  by mm    : {dict(sorted(dist(keys,3).items()))}")

# ── plot ──────────────────────────────────────────────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np

all_stems = sorted(set(k[1] for k in emboss_keys | pa_keys))
all_loops = sorted(set(k[2] for k in emboss_keys | pa_keys))

def counts_by(keys, idx, domain):
    c = dist(keys, idx)
    return [c.get(v, 0) for v in domain]

fig, axes = plt.subplots(2, 3, figsize=(15, 8))

# ── row 1: absolute counts per list ──────────────────────────────────────────
ax = axes[0, 0]
x = np.arange(len(all_stems)); w = 0.35
ax.bar(x - w/2, counts_by(emboss_keys, 1, all_stems), w, label="EMBOSS", color="#2166AC", alpha=0.85)
ax.bar(x + w/2, counts_by(pa_keys,     1, all_stems), w, label="PA",     color="#D6604D", alpha=0.85)
ax.set_xticks(x); ax.set_xticklabels(all_stems, fontsize=8)
ax.set_xlabel("Stem length (bp)"); ax.set_ylabel("Count")
ax.set_title("Hairpins by stem length"); ax.legend(fontsize=9)
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda v,_: f"{int(v):,}"))

ax = axes[0, 1]
x = np.arange(len(all_loops))
ax.bar(x - w/2, counts_by(emboss_keys, 2, all_loops), w, label="EMBOSS", color="#2166AC", alpha=0.85)
ax.bar(x + w/2, counts_by(pa_keys,     2, all_loops), w, label="PA",     color="#D6604D", alpha=0.85)
ax.set_xticks(x); ax.set_xticklabels(all_loops, fontsize=8)
ax.set_xlabel("Loop length (nt)"); ax.set_ylabel("Count")
ax.set_title("Hairpins by loop length"); ax.legend(fontsize=9)
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda v,_: f"{int(v):,}"))

# ── Venn-style stacked bar ────────────────────────────────────────────────────
ax = axes[0, 2]
categories  = ["EMBOSS\nonly", "Shared", "PA\nonly"]
values      = [len(emboss_only), len(shared), len(pa_only)]
colors_bar  = ["#2166AC", "#4DAC26", "#D6604D"]
bars = ax.bar(categories, values, color=colors_bar, alpha=0.85)
for bar, v in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50,
            f"{v:,}", ha="center", va="bottom", fontsize=10, fontweight="bold")
ax.set_ylabel("Number of hairpins")
ax.set_title("Set overlap")
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda v,_: f"{int(v):,}"))

# ── row 2: difference (EMBOSS - PA) per stem/loop ────────────────────────────
ax = axes[1, 0]
diff_stem = [dist(emboss_keys,1).get(s,0) - dist(pa_keys,1).get(s,0) for s in all_stems]
colors_d  = ["#2166AC" if d >= 0 else "#D6604D" for d in diff_stem]
ax.bar(np.arange(len(all_stems)), diff_stem, color=colors_d, alpha=0.85)
ax.axhline(0, color="black", linewidth=0.8)
ax.set_xticks(np.arange(len(all_stems))); ax.set_xticklabels(all_stems, fontsize=8)
ax.set_xlabel("Stem length (bp)"); ax.set_ylabel("EMBOSS − PA")
ax.set_title("Difference by stem length\n(blue = more in EMBOSS, red = more in PA)")

ax = axes[1, 1]
diff_loop = [dist(emboss_keys,2).get(l,0) - dist(pa_keys,2).get(l,0) for l in all_loops]
colors_d  = ["#2166AC" if d >= 0 else "#D6604D" for d in diff_loop]
ax.bar(np.arange(len(all_loops)), diff_loop, color=colors_d, alpha=0.85)
ax.axhline(0, color="black", linewidth=0.8)
ax.set_xticks(np.arange(len(all_loops))); ax.set_xticklabels(all_loops, fontsize=8)
ax.set_xlabel("Loop length (nt)"); ax.set_ylabel("EMBOSS − PA")
ax.set_title("Difference by loop length")

# ── genomic position of unique hairpins ──────────────────────────────────────
ax = axes[1, 2]
genome_len = load.genome.length
bin_size   = 5000
bins       = range(0, genome_len + bin_size, bin_size)
emboss_pos = [k[0] for k in emboss_only]
pa_pos     = [k[0] for k in pa_only]
ax.hist(emboss_pos, bins=bins, color="#2166AC", alpha=0.6, label=f"EMBOSS-only ({len(emboss_only):,})")
ax.hist(pa_pos,     bins=bins, color="#D6604D", alpha=0.6, label=f"PA-only ({len(pa_only):,})")
ax.set_xlabel("Genomic position (bp)")
ax.set_ylabel("Count per 5 kb bin")
ax.set_title("Genomic distribution of unique hairpins")
ax.legend(fontsize=9)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda v,_: f"{int(v/1000)}k"))

fig.suptitle("Comparison: EMBOSS hairpin list vs PA hairpin list\n"
             f"(EMBOSS: {len(emboss_list):,}  |  PA: {len(pa_list):,}  |  "
             f"Shared: {len(shared):,}  |  EMBOSS-only: {len(emboss_only):,}  |  PA-only: {len(pa_only):,})",
             fontsize=11)

plt.tight_layout()
out_dir = Path(__file__).parent
plt.savefig(out_dir / "hairpin_list_comparison.pdf", dpi=150, bbox_inches="tight")
plt.savefig(out_dir / "hairpin_list_comparison.png", dpi=150, bbox_inches="tight")
print("\nPlot saved: hairpin_list_comparison.pdf / .png")
